// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlumbobForge.Backend.Database;

#nullable disable

namespace PlumbobForge.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801125011_AddIsUserTagged")]
    partial class AddIsUserTagged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PlumbobForge.Backend.Database.ConfigEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfigEntities");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.ConfigSetsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConfigEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SetsEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfigEntityId");

                    b.HasIndex("SetsEntityId");

                    b.ToTable("ConfigSetsEntities");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.MetaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CASCategories")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompleteFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FileSize")
                        .HasColumnType("REAL");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filehash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUserTagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manifest")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceID")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SetsEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailID")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SetsEntityId");

                    b.ToTable("MetaEntities");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.SetsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentSetsEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentSetsEntityId");

                    b.ToTable("SetsEntities");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.SettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConfigEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigEntityId");

                    b.ToTable("SettingEntities");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.ConfigSetsEntity", b =>
                {
                    b.HasOne("PlumbobForge.Backend.Database.ConfigEntity", "ConfigEntity")
                        .WithMany("ConfigSetsEntities")
                        .HasForeignKey("ConfigEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlumbobForge.Backend.Database.SetsEntity", "SetsEntity")
                        .WithMany()
                        .HasForeignKey("SetsEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigEntity");

                    b.Navigation("SetsEntity");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.MetaEntity", b =>
                {
                    b.HasOne("PlumbobForge.Backend.Database.SetsEntity", "SetsEntity")
                        .WithMany("MetaEntities")
                        .HasForeignKey("SetsEntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SetsEntity");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.SetsEntity", b =>
                {
                    b.HasOne("PlumbobForge.Backend.Database.SetsEntity", "ParentSetsEntity")
                        .WithMany("Children")
                        .HasForeignKey("ParentSetsEntityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentSetsEntity");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.SettingEntity", b =>
                {
                    b.HasOne("PlumbobForge.Backend.Database.ConfigEntity", "ConfigEntity")
                        .WithMany("SettingEntities")
                        .HasForeignKey("ConfigEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigEntity");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.ConfigEntity", b =>
                {
                    b.Navigation("ConfigSetsEntities");

                    b.Navigation("SettingEntities");
                });

            modelBuilder.Entity("PlumbobForge.Backend.Database.SetsEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MetaEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
